# 201 Torch and Numpy

In [17]:
import torch
import numpy as np

In [18]:
# convert numpy to tensor or vise versa
np_data = np.arange(6).reshape((2, 3))
torch_data = torch.from_numpy(np_data)
tensor2array = torch_data.numpy()
print(
    '\nnumpy array:\n', np_data,          # [[0 1 2], [3 4 5]]
    '\ntorch tensor:\n', torch_data,      #  0  1  2 \n 3  4  5    [torch.LongTensor of size 2x3]
    '\ntensor to array:\n', tensor2array, # [[0 1 2], [3 4 5]]
    sep="",
)


numpy array:
[[0 1 2]
 [3 4 5]]
torch tensor:
tensor([[0, 1, 2],
        [3, 4, 5]], dtype=torch.int32)
tensor to array:
[[0 1 2]
 [3 4 5]]


In [19]:
a = np.arange(8).reshape((4,2))
torch_a = torch.from_numpy(a)
torch_a
renp = torch_a.numpy()
renp

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [20]:
# abs
data = [-1, -2, 1, 2]
tensor = torch.FloatTensor(data)  # 32-bit floating point
print(
    '\nabs',
    '\nnumpy: ', np.abs(data),          # [1 2 1 2]
    '\ntorch: ', torch.abs(tensor)      # [1 2 1 2]
)


abs 
numpy:  [1 2 1 2] 
torch:  tensor([1., 2., 1., 2.])


In [21]:
tensor.abs()

tensor([1., 2., 1., 2.])

In [22]:
# sin
print(
    '\nsin',
    '\nnumpy: ', np.sin(data),      # [-0.84147098 -0.90929743  0.84147098  0.90929743]
    '\ntorch: ', torch.sin(tensor)  # [-0.8415 -0.9093  0.8415  0.9093]
)


sin 
numpy:  [-0.84147098 -0.90929743  0.84147098  0.90929743] 
torch:  tensor([-0.8415, -0.9093,  0.8415,  0.9093])


In [23]:
tensor.sigmoid()

tensor([0.2689, 0.1192, 0.7311, 0.8808])

In [24]:
tensor.exp()

tensor([0.3679, 0.1353, 2.7183, 7.3891])

In [25]:
# mean
print(
    '\nmean',
    '\nnumpy: ', np.mean(data),         # 0.0
    '\ntorch: ', torch.mean(tensor)     # 0.0
)


mean 
numpy:  0.0 
torch:  tensor(0.)


In [26]:
# matrix multiplication
data = [[1,2], [3,4]]
tensor = torch.FloatTensor(data)  # 32-bit floating point
# correct method
print(
    '\nmatrix multiplication (matmul)',
    '\nnumpy: ', np.matmul(data, data),     # [[7, 10], [15, 22]]
    '\ntorch: ', torch.mm(tensor, tensor)   # [[7, 10], [15, 22]]
)


matrix multiplication (matmul) 
numpy:  [[ 7 10]
 [15 22]] 
torch:  tensor([[ 7., 10.],
        [15., 22.]])


In [34]:
tensor*tensor

tensor([[ 1.,  4.],
        [ 9., 16.]])

In [ ]:
    """
    WITH time AS
    (
        SELECT DATE(block_) AS DAY
        FROM *
    )
    SELECT COUNT(1) AS transaction, trans_date
    FROM time
    GROUP BY trans_date
    ORDER BY trans_date
    """