# 202 Variable


In [1]:
import torch
from torch.autograd import Variable

In [2]:
tensor = torch.FloatTensor([[1,2],[3,4]])            # build a tensor
variable = Variable(tensor, requires_grad=True)      # build a variable, usually for compute gradients

print(tensor)       # [torch.FloatTensor of size 2x2]
print(variable)     # [torch.FloatTensor of size 2x2]

tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [3., 4.]], requires_grad=True)


Till now the tensor and variable seem the same.

However, the variable is a part of the graph, it's a part of the auto-gradient.


In [3]:
t_out = torch.mean(tensor*tensor)       # x^2
v_out = torch.mean(variable*variable)   # x^2
print(t_out)
print(v_out)

tensor(7.5000)
tensor(7.5000, grad_fn=<MeanBackward0>)


In [4]:
v_out.backward()    # backpropagation from v_out

$$ v_{out} = {{1} \over {4}} sum(variable^2) $$

the gradients w.r.t the variable, 

$$ {d(v_{out}) \over d(variable)} = {{1} \over {4}} 2 variable = {variable \over 2}$$

let's check the result pytorch calculated for us below:

In [5]:
variable.grad

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])

In [6]:
variable # this is data in variable format

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)

In [7]:
variable.data # this is data in tensor format

tensor([[1., 2.],
        [3., 4.]])

In [8]:
variable.data.numpy() # numpy format

array([[1., 2.],
       [3., 4.]], dtype=float32)

Note that we did `.backward()` on `v_out` but `variable` has been assigned new values on it's `grad`.

As this line 
```
v_out = torch.mean(variable*variable)
``` 
will make a new variable `v_out` and connect it with `variable` in computation graph.